name: Portfolio Analysis

on:
  schedule:
    - cron: "30 18 * * 0"
    # - cron: "30 18 * * 3"

jobs:
  portfolio-analysis:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Add current working directory to PATH
        run: |
          echo "$(pwd)" >> $GITHUB_PATH

      - name: Verify PATH
        run: echo $PATH

      - name: Verify PYTHONPATH
        run: echo $PYTHONPATH

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Analysis script
        run: python run_scripts/analysis.py
        working-directory: .

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated analysis update"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin master
