name: Download data

on:
  schedule:
    - cron: "30 17 * * *"

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Add current working directory to PATH
        run: |
          echo "$(pwd)" >> $GITHUB_PATH

      - name: Verify PATH
        run: echo $PATH

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run download script
        run: python run_scripts/github_download.py

      # - name: Run Notebooks
      #   run: find . -name "*.ipynb" -print0 | xargs -0 -I {} jupyter nbconvert --execute --to notebook --inplace "{}"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated data update"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin master
